### ISSUE TITLE
docker stack deploy support?

### ISSUE THREAD

**Issue by cheneyweb** [rajeevshukla/spring-microservices-with-docker#1]
Does this soultion support docker stack deploy?
I have try,but when I access
http://localhost:15672
only one node show in the web console

how can it deploy multi consul and multi rabbitmq?

**Comment by rajeevshukla** [comment]
It does not support. Though I have tried to do that [check here](https://github.com/rajeevshukla/spring-microservices-with-docker/blob/master/rabbitmq_clustering/docker-compose-rabbitmq-cluster.yml). 

Will get back to you once done.  Will try. 

Meanwhile, you can give it a try

**Comment by cheneyweb** [comment]
@rajeevshukla 
OMG，it does not support....
it too bad to hear that message,I have try everyway for it

First I doubt the rabbitmq could find out each other is because the service name in swarm is always append stack name with prefix，for example my stack deploy comand like follow:
`
docker stack deploy --prune -c docker-compose.yml mq
`
the mq is my stack name，and docker service show me:

![image](https://user-images.githubusercontent.com/24515746/50038192-a4961f00-0056-11e9-8045-f4e673d5576e.png)


so I modify the docker-compose.yml，change rabbitmq to mq_rabbitmq，and consul to mq_consul，I though it will make the rabbitmq connect consul

the result is the consol seems work find，the follow is the consul screen shoot

![image](https://user-images.githubusercontent.com/24515746/50038188-97793000-0056-11e9-957e-8bc00cc8d808.png)

![image](https://user-images.githubusercontent.com/24515746/50038199-b8da1c00-0056-11e9-85b0-65612413ef88.png)

it show the consul has already find out 2 rabbitmq server
`
but with http://localhost:15672
`
![image](https://user-images.githubusercontent.com/24515746/50038226-18d0c280-0057-11e9-850a-91df2c96d897.png)

it only one node in the web console

but I notice every time access，the name will change to another rabbitmq，so I doubt it may be the reason with swarm network

I have try to set network with external:true，but it still not wrok

There is very little information about rabbitmq and docker，I have google all night，I have check rabbitmq official doc and docker swarm doc and a lot of github project，but still can not work with it

your github project is the only one which most close with this solution，I am so exited to read your project and make one node deploy success with docker compose.

I am always believe the docker swarm is the real future(k8s is to complicated，not beautiful)
I have deploy a lot of service with docker swarm，and all work great，mq cluster with swarm is a really good solution

the follow is my docker-compose.yml，I hope I could find someone to solve this problem，thanks a lot

>
version: '3.7'
services:
  consul:
    image: consul:latest
      # labels: [app=amqp-consul]
    ports:
      # - "8400:8400"
      - "8500:8500"
      # - "8600:53" #DNS port
    networks:
      - amqp
    environment:
      - 'CONSUL_BIND_INTERFACE=eth0'
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}'
    command: agent -server -ui -client=0.0.0.0 -bootstrap-expect=1 -retry-join=mq_consul
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
        # restart_policy:
        #     condition: on-failure
        #     delay: 5s
        #     max_attempts: 3
        #     window: 120s
        # update_config:
        #     parallelism: 1
        #     delay: 10s
        #     failure_action: continue
  rabbitmq:
    image: cheney/rabbitmq-consul:latest
      # labels: [app=amqp-rabbitmq]
    ports:
      - "5672:5672"
      - "15672:15672"
      # - "25672:25672"
      # - "15671:15671"
      # - "4369:4369"
      # - "5671:5671"
    networks:
      - amqp
    environment:
      - 'AUTOCLUSTER_TYPE=consul'
      - 'AUTOCLUSTER_CLEANUP=true'
      - 'CONSUL_HOST=mq_consul'
      - 'CONSUL_PORT=8500'
      - 'CONSUL_SVC=rabbitmq'
      - 'CONSUL_SVC_ADDR_AUTO=true'
      - 'CLEANUP_WARN_ONLY=false'
      - 'RABBIMQ_ERLANG_COOKIE=secrect'
      - 'RABBITMQ_USE_LONGNAME=true'
      # - 'RABBITMQ_DEFAULT_VHOST=/'
      # - 'RABBITMQ_DEFAULT_USER=admin'
      # - 'RABBITMQ_DEFAULT_PASS=123456'
    deploy:
      replicas: 1
      # restart_policy:
      #     condition: on-failure
      #     delay: 15s
      #     max_attempts: 3
      #     window: 120s
      # update_config:
      #     parallelism: 2
      #     delay: 20s
      #     failure_action: continue
volumes:
  portainer:
networks:
  amqp:
    external: true

**Comment by cheneyweb** [comment]
I also try `docker exec -it` into every container

I ping everyone with hostname, it all connect great

I can not understand why rabbitmq can't find each other?

what the difference with docker create service with docker stack deploy?

it seems every parms all the same，include the network

**Comment by rajeevshukla** [comment]
I think I had come across to the same situation where it was just overriding the same hostname. I didn't get success to implement it. The only option was to do it,  "manually" which I didn't like. 

Thanks,
